### ISSUE TITLE
Version of in-shop dataset

### ISSUE THREAD

**Issue by feiyuchen7** [Confusezius/Deep-Metric-Learning-Baselines#10]
Hi
just wondering which version of in-shop dataset did you use? Since there are two versions in the page (one normal and one high resolution) and the high resolution one needs a password.

Thanks

**Comment by Confusezius** [comment]
Hi there!

Thanks for pointing this out! 
Benchmark and Baseline-values are computed with the basic `img.zip`; the high resolution version seems to a recent(-ish) addition to the dataset.
