### ISSUE TITLE
is the file 'pretrainedmodels.py' missing?

### ISSUE THREAD

**Issue by zhweiGuo** [Confusezius/Deep-Metric-Learning-Baselines#13]
`File "Deep-Metric-Learning-Baselines/netlib.py", line 21, in <module>
    import pretrainedmodels as ptm
ModuleNotFoundError: No module named 'pretrainedmodels'`

I run the code then get the problem, Thank you very much for your help.

**Comment by Confusezius** [comment]
Hey there! If you look at 
```
Install.sh
```
you'll see that 
```
pretrainedmodels
```
Is a pip-installable library for PyTorch network weights :).

**Comment by zhweiGuo** [comment]
@Confusezius Thank you very much.
