### ISSUE TITLE
Because the use of faiss, the windows is not supported

### ISSUE THREAD

**Issue by xinheblue** [Confusezius/Deep-Metric-Learning-Baselines#16]
Unable to use in windows,  have a solution?

**Comment by Confusezius** [comment]
While this is true, we do have the file `auxiliaries_nofaiss.py` which doesn't use faiss and should work under Windows! Note however that it hasn't been extensively tested! Other than that, feel free to take a look at the https://github.com/bitsun/faiss-windows project, who are reimplementing faiss for Windows!

**Comment by alextaymx** [comment]
Hi Author, in the losses.py, there's an import of faiss at line 20, may i know how to skip that? i've changed the auxiliaries.py import into auxiliaries_nofaiss.py
