### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by martinper** [Confusezius/Deep-Metric-Learning-Baselines#18]
I cloned the repo, ran the install.sh script and tried running the Standard_Training.py file, but as soon as the network starts training, I get the error 

> RuntimeError: CUDA out of memory. Tried to allocate 42.88 MiB (GPU 0; 7.79 GiB total capacity; 6.35 GiB already allocated; 46.38 MiB free; 601.50 KiB cached)

I am using a 2070 Super GPU with 8 GB of vram. Is this too little to run the baseline, or do you think there is some other problem?

Thank you in advance

**Comment by martinper** [comment]
Never mind, I lowered the batch size and now it runs fine.

**Comment by alextaymx** [comment]
I am getting this error: MemoryError: Unable to allocate 125. GiB for an array with shape (16803752826,) and data type float64

this error comes from auxiliaries_nofaiss.py, may i know what's wrong here? Would appreciate if anyone could help
