### ISSUE TITLE
Question about method 'semihardsampling' of class 'Tuplesampler'

### ISSUE THREAD

**Issue by kdwonn** [Confusezius/Deep-Metric-Learning-Baselines#20]
In lines 150 and 152, it seems like the method 'semihardsampling' acts like MS mining('Multi Similarity Loss with General Pair Weighting', CVPR2019), not semi-hard sampling.

```
neg_mask = np.logical_and(neg,d<d[np.where(pos)[0]].max())
pos_mask = np.logical_and(pos,d>d[np.where(neg)[0]].min())
```

In terms of similarity, these lines seem equivalent to MS mining with $\epsilon = 0$ to me.
Could you please check it again?

**Comment by Confusezius** [comment]
Thanks for noticing! I have included the appropriate semihard implementation, which achieves comparable, though slightly worse results than what I have now dubbed "softhard" sampling, which is essentially hard tuple sampling, just softened (i.e. sampling negatives from those samples closer than the furthest positive, and vice versa for the positive selection). This also means that this is essentially the "opposite" variant to the sampling proposed in the MS paper.
