### ISSUE TITLE
Add Person Re-Identification Dataset

### ISSUE THREAD

**Issue by hfutzzw** [Confusezius/Deep-Metric-Learning-Baselines#21]
Such as Market1501, DukeMTMC Re-ID, CUHK, MSMT17 and etc.

**Comment by Confusezius** [comment]
The main idea of this repo is to provide a starting point for Deep Metric Learning based research, which has less focus on person ReId. While I think it would be a great addition, I will likely not have the time to do that in the near future - however I'm always open to pull requests :)
