### ISSUE TITLE
about the organization of Cars196

### ISSUE THREAD

**Issue by czzerone** [Confusezius/Deep-Metric-Learning-Baselines#23]
hello, I want to reproduce your result on Cars196, but when i download the dataset from the official website, the organization of the dataset doesn't like the one you provide in the readme. Could you please provide a hint or the code of how to handle these data. Thanks :)

**Comment by Confusezius** [comment]
That seems weird that it's not the case, but you can go to  the successor of this repo, https://github.com/Confusezius/Revisiting_Deep_Metric_Learning_PyTorch, which has Dropbox links to download each dataset in exactly the layout required. Hope that helps :).
