### ISSUE TITLE
If I understand your code correctly...

### ISSUE THREAD

**Issue by chengchu88** [Confusezius/Deep-Metric-Learning-Baselines#3]
Hello sir,

In the file 'auxiliaries.py', line 391:

sample_idxs = np.random.choice(np.arange(len(gallery_feature_matrix_all)), n_image_samples)

If I understand your code correctly, should 'gallery_feature_matrix_all' be 'query_feature_matrix_all'?

Thanks

**Comment by Confusezius** [comment]
Hi there!

You are right! Going by meaning and to avoid errors on datasets with similar layout that are not the In-Shop dataset, it should be `len(query_feature_matrix_all)`. I will adjust this.

However as a sidenote: This does not change any previously computed results, the numerical results are computed correctly (just checked again), and the qualitative results are still showing the closest gallery images given a query image, its just the random selection of query images to visualize that could change.

Thanks for pointing that out :).

**Comment by chengchu88** [comment]
Thanks for the confirmation. In my case the len(query_feature_matrix_all)
is less than the len(gallery_feature_matrix_all), so I need to change it.
Best,
Cheng
