### ISSUE TITLE
In-Shop Clothes Retrieval

### ISSUE THREAD

**Issue by kunhe** [Confusezius/Deep-Metric-Learning-Baselines#5]
Not an issue of the code, just wanted to point out this dataset is available for download: 
The [DeepFashion page](http://mmlab.ie.cuhk.edu.hk/projects/DeepFashion.html) has a Google Drive link, and following that link you can find the retrieval dataset:
https://drive.google.com/drive/folders/0B7EVK8r0v71pVDZFQXRsMDZCX1E

**Comment by Confusezius** [comment]
Ok great, thanks for the info! I will include this in the README.
