### ISSUE TITLE
resizing images to 256x256

### ISSUE THREAD

**Issue by kunhe** [Confusezius/Deep-Metric-Learning-Baselines#8]
https://github.com/Confusezius/Deep-Metric-Learning-Baselines/blob/dbcd5abe2966c3398b893664bba2d61075b628d9/datasets.py#L397

I believe there's a bug in `BaseTripletDataset.transform`: during training, images are not resized to 256x256 before taking crops.

Interestingly, this did not seem to affect results by much, at least when I tested it in Online Products with Margin loss...

**Comment by bbrattoli** [comment]
Thank you for your comment.

I believe that this was by choice. Not normalizing to 256 helps as an extra augmentation.

Nevertheless, thank you for letting us know that it does not change the result much.

**Comment by kunhe** [comment]
That's good to know, thanks!
