### ISSUE TITLE
Evaluation on SOP took forever

### ISSUE THREAD

**Issue by feiyuchen7** [Confusezius/Deep-Metric-Learning-Baselines#9]
Hi
Thank you for your work and code!

I tested on CUB and CAR and it worked well but when I used SOP dataset, it seemed as it got stuck in the evaluation process, right inside the calculation of kmeans. The test values of Epoch 0 never got out and the program just got stuck there. It was the same for faiss or no_faiss setting.

Did I miss anything or could you suggest some hints to solve it?

Cheers

**Comment by Confusezius** [comment]
SOP is a big dataset, so nearest neighbour retrieval takes much longer than on e.g. CUB and CARS :). It should however finish in a matter of minutes or faster, depending on your hardware setup. You can also move the faiss computation to the GPU for increased speed.
